package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "nce",
    srcs = ["nce.py"],
    srcs_version = "PY2AND3",
    deps = [
    ],
)

py_library(
    name = "softmax",
    srcs = ["softmax.py"],
    srcs_version = "PY2AND3",
    deps = [
    ],
)
