package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "mv_mlp",
    srcs = ["mv_mlp.py"],
    srcs_version = "PY2AND3",
    deps = [
    ],
)

py_library(
    name = "mlp",
    srcs = ["mlp.py"],
    srcs_version = "PY2AND3",
    deps = [
    ],
)

py_library(
    name = "mlp_v2",
    srcs = ["mlp_v2.py"],
    srcs_version = "PY2AND3",
    deps = [
    ],
)
